### ISSUE TITLE
Invite users to community in --help flag

### ISSUE THREAD

**Issue by anujb** [Microsoft/mobile-center-cli#104]
I was spinning up a toy app using Swift and the framework (Vapor) did this delightful thing I think we can "borrow". 
```
$tmp vapor --help
Usage: vapor <new|build|run|fetch|clean|test|xcode|version|self|heroku|docker>
**Join our Slack if you have questions, need help, or want to contribute: http://vapor.team**
```

I don't know if we have a public community chat yet, but it would be a nice little touch to invite people to proactively engage with us as they start to learn how to use the service.

**Comment by christav** [comment]
We don't currently have such a channel that I know of. The closest thing would be the intercom widget in the Mobile Center portal I guess.

**Comment by amchew** [comment]
@anujb thanks for your feedback and suggestion. We'll placed the feature in our backlog for now. If you are available sometime, I'd like to have a call with you to get more on your feedback on CLI - please email me at amchew [at] microsoft.com.
