### ISSUE TITLE
Improve the telemetry prompt

### ISSUE THREAD

**Issue by elamalani** [Microsoft/mobile-center-cli#171]
This is how the telemetry prompt looks right now:
![pasted image at 2017_04_24 10_08 am](https://cloud.githubusercontent.com/assets/4133129/25349328/451bb9d0-28d6-11e7-97fa-91d39dbb6eef.png)

**Comment by dvdsgl** [comment]
Is it a requirement to include the privacy policy link?

**Comment by dvdsgl** [comment]
Here is a simplified version, which also omits the privacy policy. I will add a mockup that includes the privacy policy as another option.

<img width="1154" alt="telemetry prompt" src="https://cloud.githubusercontent.com/assets/108197/25642460/d59dd442-2f4e-11e7-89b9-f8d64605158e.png">

**Comment by elamalani** [comment]
Not required to have privacy link but its good to have for users who want to read fine print.

**Comment by christav** [comment]
My understanding is that the privacy policy link is required as per CELA.

**Comment by amchew** [comment]
@dvdsgl @elamalani @christav closing this GitHub issue and we'll discuss this as a user scenario in our CLI Yellow Padding session on 11/03

**Comment by amchew** [comment]
@dvdsgl @elamalani @christav closing this GitHub issue and we'll discuss this as a user scenario in our CLI Yellow Padding session on 11/03
