### ISSUE TITLE
analytics sessions time-range

### ISSUE THREAD

**Issue by matt-gibbs** [Microsoft/mobile-center-cli#199]
mobile-center analytics sessions returns values for an unspecified time-range.
It doesn't correspond to the last7, last30, last60 or last90 options in the portal. 

```Session Durations
    0-10s    4
    10-30s   0
    30s-1min 0
    1-30min  1
    30min-1h 0
    >1h      0

Session Statistics
    Total Sessions               5     0%
    Average Sessions Per Day     5     100%
    Average Session Length (sec) 28.38 100%
```
![image](https://cloud.githubusercontent.com/assets/6565986/26654100/5db54f6e-460a-11e7-8b1d-e2e3dc129e03.png)

**Comment by blparr** [comment]
@matt-gibbs It shows the values from 00.00 to "Now". If we maintain it this way, we can add this information in the help functionality indicating what's the time range by default.

The other option would be re implementing to last 7/30/60 days, but I think the customization in the CLI brings more value.
