### ISSUE TITLE
Listing organizations is not very readable

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/mobile-center-cli#225]
A few suggestions:

- Display both `display_name` and `name`
- Consider constructing a URL directly from the `name` instead of showing the value plainly, similar to what we do in the UI:
<img width="588" alt="screenshot 2017-06-14 21 42 48" src="https://user-images.githubusercontent.com/406937/27151333-8dccf5b2-514a-11e7-92a8-2c2ffa50d0f6.png">

- Looking at the screenshot above, we should imo also have an indication if the organization is synced over from HockeyApp and therefore read-only

**Comment by christav** [comment]
Fxied in #235
