### ISSUE TITLE
"orgs create" should send "display_name" instead of "name"

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/mobile-center-cli#229]
Right now, it appears as if `orgs create -n "some-name"` requires the `name` attribute only.
I think this could be improved by mirroring the UI experience where we send a `display_name` and let the backend auto-generate a `name`.

**Comment by lumaxis** [comment]
Optionally, people can of course always explicitly specify a `name` but I think the `display_name` should be a required parameter in this case

**Comment by christav** [comment]
Fixed in #231
