### ISSUE TITLE
Improve "x list" commands

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/mobile-center-cli#230]
This is a follow-up to #226 

Currently, commands like `apps list` and `orgs list` output very minimal information and getting more details always requires using an additional `x show` command on a single entity to get more details.
I would suggest to come up with a format, like a table, that outputs most of the useful/necessary information right in the `list` command's output.

Something like this:

### Apps
```
| Display name | Name        | OS      | Platform | Origin        |
| ------------ | ----------- | ------- | -------- | ------------- |
| My Test App  | my-test-app | iOS     | Xamarin  | mobile-center |
| Some App     | some-app    | Windows | UWP      | hockeyapp     |
```

or 

### Organizations
```
| Display Name  | Name          | Origin        |
| ------------- | ------------- | ------------- |
| Mobile Center | mobile-center | mobile-center |
```

**Comment by christav** [comment]
Fixed in #235
