### ISSUE TITLE
Application name different from package.json name, possible extra argument for CodePush?

### ISSUE THREAD

**Issue by verluci** [Microsoft/mobile-center-cli#2423]
**Is your feature request related to a problem? Please describe.**
Currently when building a new release using Codepush, Codepush uses the package.json name to determine where to look in the ios directory. So if the package.json name is myApp, Codepush will look for /ios/myApp. However, our application is named the same everywhere (product and company share a name). We're in a monorepo (using NX and React Native), so every package name is something like @companyName/mobile. The ios folder structure however is just /ios/companyName.

**Describe the solution you'd like**
It'd be great if I could add an argument to tell the CLI where to look for iOS files. 

**Describe alternatives you've considered**
I've renamed the package for now, but that makes for a confusing situation when running NX commands. 

**Additional context**
None

**Comment by AnatolyPristensky** [comment]
Hello @verluci, according to your request I think that you can use existing arguments like `--xcode-project-file` and `--plist-file` to provide explicit path to iOS part of the project. 

Please, try it and let me know if this helps.

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from  you for a while, so I'm closing this issue. Feel free to reach out or reopen the ticket if you still have concerns or questions.
