### ISSUE TITLE
Add a link to the Microsoft Code of Conduct

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/mobile-center-cli#75]
I'm not sure if this should go into Contributing or Readme. The latter would yield greater visibility as it is always visible when visiting the repo's main page, the former fits a bit better semantically.

For a good example see https://github.com/Microsoft/mobile-center-sdk-ios/pull/196/files

**Comment by christav** [comment]
Fixed via #81. Thanks @taml!

**Comment by taml** [comment]
No problem @christav!
